--- # devspaces.yml
name: rretro
description:  Development environment for Remote Retro
# If you want to use a different Dockerfile for your DevSpace, provide the path
# here.
docker-file: Dockerfile

# If you need additional files when building your Dockerfile, such as some
# application binaries that your Dockerfile references, list the glob paths to
# include here. They are relative to this devspaces.yml file.
docker-build-includes: |
  ../../.tool-versions
  **/*
ports:
- protocol: http # can be udp|tcp|http
  port-number: 4000
  description: elixir app
- protocol: tcp # can be udp|tcp|http
  port-number: 5432
  description: postgres


environment-vars:
# Postgres Database entryponit VARS
- name: DB_HOST
  value: localhost
  description: pgsql host
- name: DB_PORT
  value: 5432
  description: pgsql port
- name: DB_NAME
  value: remote_retro
  description: pgsql  DB Name
- name: DB_USER
  value: remote_retro
  description: pgsql DB User
- name: DB_PASSWORD
  value: remote_retro
  description: pgsql DB Password
- name: RETRO_DB_HOST
  value: localhost
  description: Remote Retro DB Host

# generic `build` filter cannot be used once we have a source package named `build`.
sync-ignore: |
  .git
  .idea
  **/node_modules
  **/target
  deps
  _build
